title: Luke Cusack
baseurl: ""

author: Luke Cusack
username: ljcusack
date_format: "%-d %B %Y"

tagline: Blog posts from a Computer Science student.

github_username: ljcusack
linkedin_username: ljcusack

google_analytics:
disqus_shortname:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
